### ISSUE TITLE
Conflict with Legal Tools after forcing consent

### ISSUE THREAD

**Issue by smashm** [humhub/humhub-modules-twofa#14]
There is a reproducible conflict with Legal Tools. If consent is forced again after changes, there are too many redirects. 

![Bildschirmfoto 2021-02-16 um 15 13 44](https://user-images.githubusercontent.com/60502320/108074704-cdb4fe80-7069-11eb-898d-45a848921b1b.png)

Only chance to log in again seems to disable 2FA temporary.
![Bildschirmfoto 2021-02-16 um 15 14 14](https://user-images.githubusercontent.com/60502320/108074724-d3124900-7069-11eb-98bf-d6ad17649dbd.png)

Otherwise, it works fine at first glance, also works with Microsoft Authenticator without problems. Thanks for your good work.

**Comment by ArchBlood** [comment]
Something similar to this could be done, but it's not a complete fix

https://github.com/humhub-contrib/legal/pull/15

**Comment by buddh4** [comment]
See https://github.com/humhub-contrib/legal/issues/16

**Comment by yurabakhtin** [comment]
I answered with my suggested solution here https://github.com/humhub-contrib/legal/issues/16#issuecomment-780543641

**Comment by luke-** [comment]
@yurabakhtin Can you please provide a hotfix (hardcode the "twofa" to the exceptions) for the Legal module.

**Comment by yurabakhtin** [comment]
@luke- Yes, please review PR https://github.com/humhub-contrib/legal/pull/17.
